### ISSUE TITLE
Crashing on world open using the latest Magma version

### ISSUE THREAD

**Issue by Licious17** [magmafoundation/Magma#84] opened 2020-03-04 10:24 UTC
Hi, I was informed about this project and decided to give it a try, after a bit of testing around on a test server I came across a crash on render of a ranch block from the Pixelmon mod (v 7.2.0)
Removing the tile entity externally and a simple rollback fix the issue however this is a preety significant deal for a production server. I hope this can be fixed in the near future since Magma does seem appealing.

[crash-2020-03-04_10.20.45-server.txt](https://github.com/magmafoundation/Magma-1.14/files/4286738/crash-2020-03-04_10.20.45-server.txt)

**Comment by Jay113355** [comment] 2020-03-04 19:25
Seems to be caused by a call to canDespawn() on the EntityBreeding before the entity is fully setup, 
Magma's code: 
https://github.com/magmafoundation/Magma/blob/cc62a7b625d87d50db1a7bc330a72085c25e3d7b/patches/net/minecraft/entity/EntityLiving.java.patch#L89

Pixelmons code:
```
@Override
public boolean canDespawn() {
	return pokemon.getOwnerPlayer() == null || super.canDespawn();
}
```

I'll add a null check in Pixelmon. it will be fixed in 7.2.1.

**Closed** 2020-03-06 17:03 UTC
