### ISSUE TITLE
[Issue] Server Crash on start up

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [magmafoundation/Magma#353] opened 2021-01-10 12:18 UTC
What is wrong: Server crashes on start. Hard to explain what happens.
Logs: 
(https://mcpaste.io/72b23f6c4ee5508e) Crash log as requested
(https://gist.github.com/MrWhiteFlamesYT/8b6c5892cb6471004c5fa49f2077abe2) Latest.log
Magma Version: Magma-5bff736-server
https://1drv.ms/u/s!Ah9Z8o5_Q1YQkshG2TBnx2yJOqWz-g
(and modlist, all up to date it is in HTML form now sorry)
Modpack:
https://www.curseforge.com/minecraft/modpacks/zerog-craft
Plugin List:
https://imgur.com/hVWDZKu
OS:
Windows 10 Enterprise (Testing local)
Main server it gets uploaded to is a 
GNU/Linux 10 (buster)

**Comment by kwright02** [comment] 2021-01-10 17:33
You're using an incompatible version of IC2

**Comment by MrWhiteFlamesYT** [comment] 2021-01-10 20:44
ok what IC2 do you suggest

**Comment by SanderWxD** [comment] 2021-01-12 16:41
Tried IC2 version:
2.8.170
2.8.178
2.8.221
None work. SprongeForge does work with all 4, so I doubt that it is IC2 here.

**Comment by SanderWxD** [comment] 2021-01-12 19:01
Further testing shows that the presence of Gregtech (any version), makes the server crash.

**Comment by KorewaLidesu** [comment] 2021-01-13 06:17
[Check this out](https://github.com/kwright02/MagmaCompatibilityCollection/blob/master/1.12.2/incompatibilities/ProjectE-GTCE-2.modgroup.incompatbile)

**Comment by Mswlolcatz** [comment] 2021-01-13 18:49
> Tried IC2 version:
> 2.8.170
> 2.8.178
> 2.8.221
> None work. SprongeForge does work with all 4, so I doubt that it is IC2 here.

Magma is spigot based, spigot and sponge plugins are generally not universal - thus they work on spongeforge and not magma. Unless you're already using a spigot version of IC2 that I've not heard of.

**Comment by SanderWxD** [comment] 2021-01-13 18:55
Euhh IC2 (IndustrialCraft2) is a Forge mod. Should work on both.
The comparison with Spongeforge was more to show that it's not a bug in the mod but a bug in the server software, Magma, in this case.

**Comment by Mswlolcatz** [comment] 2021-01-13 19:01
yuhh, just realised mb. Did you guys solve the issue in the end?

**Comment by KorewaLidesu** [comment] 2021-01-14 11:54
It is the same as #318 if you wonder.

**Comment by Hexeption** [comment] 2021-01-23 19:00
Fixed in 537f1d62dca8c7f1d2b6eb7a45d618885eade5bd

**Closed by Hexeption** 2021-01-23 19:00 UTC
Labels: support
