### ISSUE TITLE
[BUG]EnderIO permission denied when try to use items and machines

### ISSUE THREAD

**Issue by maggotmick** [magmafoundation/Magma#91] opened 2020-03-22 23:17 UTC
When you craft and place any machine and try to open the GUI or even use soul bottles, dark steel tools or armor a message like when you sleep and theres monsters nearby appears "Permission Denied" 

**To Reproduce**
1. Craft sterling generator'
2. Place it on the floor
3. Right click on the machine to try to open the GUI
4. A message appears "Permission Denied"

**Expected behavior**
Open the machine GUI and put coal on it

**Screenshots**
https://i.imgur.com/intITZZ.png

**Info (please complete the following information):**
- Mod Name: EnderIO 
 - Mod Version: 5.1.55
 - Magma Version: Magma Dev master-6abd63f

**Additional context**
When i search on my server log i found this line:

`[22:48:38] [Server thread/WARN] [FML]: Replacing com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler with org.magmafoundation.magma.commands.permission.BukkitPermissionsHandler
`

To solve it i edit magma.yml and change "true" to "false"

'  bukkitPermissionHandler:
    enable: false'

**Comment by UeberallGebannt** [comment] 2020-03-26 14:37
Try to disable the permission handler in the magma.yml

**Comment by kwright02** [comment] 2020-03-26 22:19
I’ll take a look at this in more detail soon

**Comment by DeathSmurf** [comment] 2020-04-01 20:27
Hello kwright02, the same error occurs to me, the commands that trigger the mods do not work in common players, they only work with those who have op, despite having false bukkitPermissionHandler from the magma.yml file, this replaces me on console "org.magmafoundation.magma.commands.permission.BukkitPermissionsHandler"

**Comment by kwright02** [comment] 2020-04-01 20:28
If you use the latest version of Magma this should be fixed as long as your Magma.yml is correct. If it's not correct, then it still won't work. Please try the latest Magma jar and if the error persists send your Magma.yml here.

**Comment by kwright02** [comment] 2020-04-01 20:31
@Hexeption Close please

**Comment by DeathSmurf** [comment] 2020-04-01 20:34
Ok, thanks for replying, I'll take a look at the _latest version_. 
I will **notify you if the problem is** **fixed**.

**Comment by HenryLoenwind** [comment] 2020-04-07 08:24
Sorry, but this needs to be fixed in a way that it works in the default configurations. We're getting flooded with complaints about this.

**Comment by kwright02** [comment] 2020-04-08 14:56
@HenryLoenwind If you have the correct configuration file then setting the bukkitPermissionBridge to false will fix your issue if you're using just EnderIO. For all other instances, the way the server is set up, each mod will handle it commands differently. Some, like EnderIO, will allow base users to run the commands without permission nodes. Others will require a permission node because the player isn't an Operator. The easiest way to fix this is allow the bukkitPermissionBridge in the magma.yml and use something like PermissionsEx or LuckyPerms. The forge mod command permissions are structured like this: class-name.command-name
To get the class name you'll need to either speak with the mod author or decompile the mod jar to find the class file where it's from. 

@Hexeption this should be closed or at least removed from Bugs

**Comment by HenryLoenwind** [comment] 2020-04-08 15:03
You might want to check who you're talking to...

And also have a second look at Forge's permission system. When a permission node is registered, one of the parameters is a DefaultPermissionLevel. Any permission handler should respect that and use it as default as long as no override exists.

**Comment by kwright02** [comment] 2020-04-08 21:42
What do you mean by check who I'm talking to? I'm simply explaining how the permissions work on Magma so that the OP can use magma the way he desires. Using the format that I mentioned is what you would want to do when using something like LuckPerms to handle the permissions

**Closed** 2020-04-09 01:48 UTC
Labels: bug

**Comment by tyler489** [comment] 2020-04-11 23:33
@kwright02 Henry is the lead and currently the only dev of enderio. that's what he ment by check who you are talking to.

**Comment by kwright02** [comment] 2020-04-12 14:06
Ok, so I'm just supposed to know that he's the lead dev of ederio? I wasn't being disrespectful and all he had to do was say he's the lead dev. Just because he's the lead dev doesn't give him a higher position than me. I'm not locking this thread.
