### ISSUE TITLE
[BUG] Death/Health bug

### ISSUE THREAD

**Issue by Hedrixz** [magmafoundation/Magma#156] opened 2020-06-09 19:29 UTC
**Describe the bug**
A clear and concise description of what the bug is:
I'm using the RLCraft modpack and when players lose all health they don't die.
**To Reproduce**
1. Download RLCraft and use with Magma
2. Try do die (Try this twice)

**Expected behavior**
A clear and concise description of what you expected to happen:
You die and respawn at a random point or at a your spawnpoint (If you've set one)
**Screenshots**
If applicable, add screenshots to help explain your problem:
![2020-06-09_21 25 13](https://user-images.githubusercontent.com/60573981/84190989-19091d00-aa98-11ea-8292-e7c1a8daf148.png)
![image](https://user-images.githubusercontent.com/60573981/84191819-5e7a1a00-aa99-11ea-9d53-30b6c62fa762.png)
(My Health wouldn't go lower than this)

**Info (please complete the following information):**
- Mod Name: RLCraft
 - Mod Version: 2.8.2 (Latest)
 - Magma Version: Magma Dev HEAD-e20a51e
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:
Players don't respawn when they die, they just stay alive with the death animation constantly looping.

**Comment by RupticMC** [comment] 2020-06-09 19:53
It is because of the FirstAid mod. It currently does not work properly with any hybrid servers for 1.12.2. You can simply remove the mod and run RLCraft.

**Comment by Hedrixz** [comment] 2020-06-09 20:13
Will there be added support in the future?

**Comment by Hedrixz** [comment] 2020-06-09 20:33
I removed it, but now nobody can join. It spams this in console
![image](https://user-images.githubusercontent.com/60573981/84196824-16f78c00-aaa1-11ea-8a06-422cec5adce9.png)
 and the server is marked with old and vanilla in the serverlist.

**Comment by Redd56** [comment] 2020-06-09 22:22
thats cause its still starting.....

**Comment by Redd56** [comment] 2020-06-09 22:23
its probably waiting for you to confirm startup since you removed that mod
go into console and type /fml confirm

**Comment by Redd56** [comment] 2020-06-09 22:23
merge with https://github.com/magmafoundation/Magma/issues/86

**Comment by Hexeption** [comment] 2020-06-09 22:27
Duplicate of #86

**Closed by Hexeption** 2020-06-09 22:27 UTC
Labels: bug
